[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "The Microlearning Model for Cybersecurity Training: Protecting Business Data and Assets Through Employee Education"
